config/routes.rb
Organizador::Application.routes.draw do
  get "empleados/create"
  get "empleados/update"
  get "empresas/create"
  get "empresas/update"

 resources :empresas
 resources :empleados
 resources :sessions, only: [:new, :create, :destroy]

end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  
  
  validates :nombre, presence: true
  validates :correo_electronico, presence: true,  uniqueness: true
  validates :rfc, presence: true
  validates :empresa_id, presence: true
  validates :password, presence: true
  
 # has_secure_password
 # validates :password, length: { minimum: 6 }
  
  belongs_to :empresa
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  
  validates :nombre, presence: true,  uniqueness: { case_sensitive: false }
  
  has_many :empleados
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  def index
    @empleados = Empleado.all
  end
  
   

  def new
    @empleado = Empleado.new
    @empresas = Empresa.all
  end

  def create
   # @empresa = Empresa.new(params[:empresa])
    @empleado = Empleado.new
    @empleado.nombre = params[:nombre]

    @empleado.correo_electronico = params[:correo_electronico]
    @empleado.rfc = params[:rfc]
    @empleado.empresa_id = params[:empresa_id]
    @empleado.password = params[:password]
 #   @empleado.password_confirmation = params[:confirmation_password]
    if  @empleado.save
   #  @empresa.save!
       flash[:notice]  = "El Empleado ha sido guardado"
        redirect_to controller: 'empresas', action: 'index'
    else
       flash[:notice]  = "Ese correo ya ha sido registrado"
        redirect_to action: 'new'

    end
  end


  def edit
    @empleado = Empleado.find(params[:id])
    @empresas = Empresa.all
  end

  def update
    @empleado = Empleado.new
    @empleado.nombre = params[:nombre]

    @empleado.correo_electronico = params[:correo_electronico]
  #  @empleado.rfc = params[:rfc]
    @empleado.empresa_id = params[:empresa_id]
    @empleado.password = params[:password]
    
    if  @empleado.save
   #  @empresa.save!
       flash[:notice]  = "El Empleado ha sido guardado"
        redirect_to controller: 'empresas', action: 'index'
    else
       flash[:notice]  = "Ese correo ya ha sido registrado"
       redirect_to action: 'edit'
      #redirect_to empresas_new_path, :notice => "Hubo un error al guardar en base de datos"
      #render "new"
    end
    
  end

  def destroy
     @empleado = Empleado.find(params[:id])
     @empleado.destroy!
     redirect_to empleados_path, :notice => "El Empleado ha sido eliminado"
     
  end
  
  
  
  def sign_in
    
  end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  def index
    @empresas = Empresa.all
   

  end

  def show
    @empresa = Empresa.new
    @empresa.nombre = params[:nombre]
    @empresa.calle = params[:calle]
    @empresa.colonia = params[:colonia]
    @empresa.numero_ext = params[:numero_ext]
    @empresa.numero_int = params[:numero_int]
    @empresa.codigo_postal = params[:codigo_postal]
    @empresa.ciudad = params[:ciudad]
    @empresa.pais = params[:pais]
  end

  def new
    @empresa = Empresa.new
    @Empleados = Empleado.new
  end

  def create
   # @empresa = Empresa.new(params[:empresa])
    @empresa = Empresa.new
    @empresa.nombre = params[:nombre]
    @empresa.calle = params[:calle]
    @empresa.colonia = params[:colonia]
    @empresa.numero_ext = params[:numero_ext]
    @empresa.numero_int = params[:numero_int]
    @empresa.codigo_postal = params[:codigo_postal]
    @empresa.ciudad = params[:ciudad]
    @empresa.pais = params[:pais]
    if  @empresa.save
   #  @empresa.save!
       flash[:notice]  = "Tu sucursal ha sido guardada"
        redirect_to empresas_path
    else
       flash[:notice]  = "El nombre de la sucursal ya existe"
        redirect_to action: 'new'
      #redirect_to empresas_new_path, :notice => "Hubo un error al guardar en base de datos"
      #render "new"
    end
  end


  def edit
    @empresa = Empresa.find(params[:id])
     @empleados = Empleado.where("empresa_id = ?", params[:id])
  end

  def update
    @empresa = Empresa.find(params[:id])
    @empresa.nombre = params[:nombre]
    @empresa.calle = params[:calle]
    @empresa.colonia = params[:colonia]
    @empresa.numero_ext = params[:numero_ext]
    @empresa.numero_int = params[:numero_int]
    @empresa.codigo_postal = params[:codigo_postal]
    @empresa.ciudad = params[:ciudad]
    @empresa.pais = params[:pais]
  #  @empresa.update!
  #  redirect_to empresas_path, :notice => "Tu sucursal ha sido actualizada"
    
   if  @empresa.save
   #  @empresa.save!
       flash[:notice]  = "Tu sucursal ha sido guardada"
        redirect_to empresas_path
    else
       flash[:notice]  = "El nombre de la sucursal ya existe"
        redirect_to action: 'edit'
      #redirect_to empresas_new_path, :notice => "Hubo un error al guardar en base de datos"
      #render "new"
    end
  end

  def destroy
     @empresa = Empresa.find(params[:id])
     @empresa.destroy!
     redirect_to empresas_path, :notice => "Tu sucursal ha sido eliminada"
     
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @empleado = Empleado.find_by(correo_electronico: params[:session][:email].downcase)
    if @empleado && (@empleado.password == params[:session][:password])
      flash[:notice]  = "Login Exitoso"
      redirect_to empresas_path
    else
      flash[:notice]  = "Hubo un problema con tus credenciales"
      redirect_to action: 'new'
    end
  end





  def destroy
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/empleados/destroy.html.erb
<h1>Empleados#destroy</h1>
<p>Find me in app/views/empleados/destroy.html.erb</p>

app/views/empleados/edit.html.erb
<script type="text/javascript">

function validateEmpleado()
{
 
   if( document.input.nombre.value == "" )
   {
   	 document.getElementById("Error").innerHTML="<li>Error: Nombre del empleado es necesario para crear un nuevo empleado</li>";
     //alert( "Nombre del empleado es necesario para crear un nuevo empleado" );
     document.input.nombre.focus() ;
     return false;
   }
   if( document.input.correo_electronico.value == "" )
   {
   	 document.getElementById("Error").innerHTML="<li>Error: Correo Electronico es necesario para crear un nuevo empleado</li>";
     alert( "Correo Electronico es necesario para crear un nuevo empleado" );
     document.input.correo_electronico.focus() ;
     return false;
   }
   if( document.input.rfc.value == "" )
   {
     alert( "RFC es necesario para crear un nuevo empleado" );
     document.input.rfc.focus() ;
     return false;
   }if( document.input.empresa_id.value == "" )
   {
     alert( "Empresa es necesaria para crear un nuevo empleado" );
     document.input.empresa_id.focus() ;
     return false;
   }
   if( document.input.password.value == "" )
   {
     alert( "Password es necesario para crear un nuevo empleado" );
     document.input.password.focus() ;
     return false;
   }
   
   if( document.input.password.value != document.confirmacion_password.value )
   {
     alert( "Tu Password y su Confirmacion no concuerdan" );
     document.input.password.focus() ;
     return false;
   }
   
   var emailID = document.input.correo_electronico.value;
   atpos = emailID.indexOf("@");
   dotpos = emailID.lastIndexOf(".");
   if (atpos < 1 || ( dotpos - atpos < 2 )) 
   {
       alert("Por favor escriba un Correo Electronico valido")
       document.input.correo_electronico.focus() ;
       return false;
   }
   
   
   
   return( true );
}

</script>

<h1>Editar Empleado</h1>

<div id="Error"></div>

<form name="input" action="/empleados/update" method="get" onsubmit="return(validateEmpleado);">
<table>
		<tr> 
			<td>Nombre:</td> 
			<td><input type="text" name="nombre" value=<%=@empleado.nombre%> </td> 
		<tr>
 		<tr>
 			<td>Correo Electronico: </td> 
 			<td><input type="text" name="correo_electronico" value=<%=@empleado.correo_electronico%>></td> 
 		<tr>

		<tr>
 			<td>RFC:</td> 
 			<td><input type="text" name="rfc" value=<%=@empleado.rfc%> disabled></td> 
 		<tr>
 
        <tr>
 			<td>Empresa: </td> 
 			<td><select name="empresa_id">
			    <option hidden="true" value='0'>Seleccione una empresa</option>
			    <%@empresas.each do |empresa| %>
	
					<% if empresa.id == @empleado.empresa_id %>
			    	<option value=<%= empresa.id %> selected> <%= empresa.nombre %> </option>
			    	<% else %>
			    	<option value=<%= empresa.id %> > <%= empresa.nombre %> </option>
			    	<% end %>
			    <% end %>
			</select>
 		<tr>

		<tr>
 			<td>Password: </td> 
 			<td><input type="password" name="password" value=<%=@empleado.password%>></td> 
 		<tr>

		<tr>
 			<td>Confirmacion Password:</td> 
 			<td> <input type="password" name="confirmacion_password" value=<%=@empleado.password%>></td> 
 		<tr>


</table>
<input type="submit" value="Submit">
</form>

app/views/empleados/index.html.erb
<h1>Listado de Empleado</h1>
<% if @empleados != nil %>
	<h2>Empleados Existentes</h2>
	<table style="width:300px">
	<tr>
	  <td>Nombre</td>
	  <td>Correo Electronico</td> 
	  <td>RFC</td>
	  <td>Empresa id</td>
	  <td></td>
	  <td></td>
	  <td></td>
	</tr>
	
	
	<%@empleados.each do |empleado| %>
	<tr>
	  <td><%= empleado.nombre %></td>
	  <td><%= empleado.correo_electronico %></td> 
	  <td><%= empleado.rfc %></td>
	  <td><%= empleado.empresa_id %></td>
	  
      
	  
      <td><%= link_to 'Modificar', edit_empleado_path(empresa) %></td>
      <td><%= link_to 'Eliminar', empleado, method: :delete,
                                     data: { confirm: 'Estas seguro?' } %></td>
	</tr>
	<% end %>
	</table>
<% else %>
	
	<h2>No hay empleado a mostrar</h2>

<% end %>
<br>
<%= link_to "Agregar Sucursal", new_empleado_path %>
<%= link_to "Agregar Empleado", empleado_path %>

app/views/empleados/new.html.erb
<script type="text/javascript">

function validateEmpleado()
{
 
   if( document.input.nombre.value == "" )
   {
   	 document.getElementById("Error").innerHTML="<li>Error: Nombre del empleado es necesario para crear un nuevo empleado</li>";
     //alert( "Nombre del empleado es necesario para crear un nuevo empleado" );
     document.input.nombre.focus() ;
     document.input.nombre.style.border = "solid 1px red";
     return false;
   }else
   {
   	document.input.nombre.style.border = "solid 1px black";
   }
   
   if( document.input.correo_electronico.value == "" )
   {
   	 document.getElementById("Error").innerHTML="<li>Error: Correo Electronico es necesario para crear un nuevo empleado</li>";
     //alert( "Correo Electronico es necesario para crear un nuevo empleado" );
     document.input.correo_electronico.style.border = "solid 1px red";
     document.input.correo_electronico.focus() ;
     return false;
   }else
   {
   	document.input.correo_electronico.style.border = "solid 1px black";
   }
      
   var emailID = document.input.correo_electronico.value;
   atpos = emailID.indexOf("@");
   dotpos = emailID.lastIndexOf(".");
   if (atpos < 1 || ( dotpos - atpos < 2 )) 
   {
       //alert("Por favor escriba un Correo Electronico valido")
       document.getElementById("Error").innerHTML="<li>Por favor escriba un Correo Electronico valido</li>";
       document.input.correo_electronico.style.border = "solid 1px red";
       document.input.correo_electronico.focus() ;
       return false;
   }else
   {
   	document.input.correo_electronico.style.border = "solid 1px black";
   }
   
   if( document.input.rfc.value == "" )
   {
     //alert( "RFC es necesario para crear un nuevo empleado" );
     document.getElementById("Error").innerHTML="<li>RFC es necesario para crear un nuevo empleado</li>";
     document.input.rfc.style.border = "solid 1px red";
     document.input.rfc.focus() ;
     return false;
   }else
   {
   	document.input.rfc.style.border = "solid 1px black";
   }
   
   if( document.input.empresa_id.value == "0" )
   {
     //alert( "Empresa es necesaria para crear un nuevo empleado" );
     document.getElementById("Error").innerHTML="<li>Empresa es necesaria para crear un nuevo empleado</li>";
     document.input.empresa_id.style.border = "solid 1px red";
     document.input.empresa_id.focus() ;
     return false;
   }else
   {
   	document.input.empresa_id.style.border = "solid 1px black";
   }
   
   if( document.input.password.value == "" )
   {
     //alert( "Password es necesario para crear un nuevo empleado" );
     document.getElementById("Error").innerHTML="<li>Password es necesario para crear un nuevo empleado</li>";
     document.input.password.style.border = "solid 1px red";
     document.input.password.focus() ;
     return false;
   }else
   {
   	document.input.password.style.border = "solid 1px black";
   }
   
   if( document.input.confirmation_password.value == "" )
   {
     //alert( "Password es necesario para crear un nuevo empleado" );
     document.getElementById("Error").innerHTML="<li>Password es necesario para crear un nuevo empleado</li>";
     document.input.confirmation_password.style.border = "solid 1px red";
     document.input.confirmation_password.focus() ;
     return false;
   }else
   {
   	document.input.confirmation_password.style.border = "solid 1px black";
   }
   
   if( document.input.password.value != document.input.confirmation_password.value )
   {
     //alert( "Tu Password y su Confirmacion no concuerdan" );
     document.getElementById("Error").innerHTML="<li>Tu Password y su Confirmacion no concuerdan</li>";
     document.input.password.style.border = "solid 1px red";
     document.input.confirmation_password.style.border = "solid 1px red";
     document.input.password.focus() ;
     return false;
   }else
   {
   	document.input.password.style.border = "solid 1px black";
   	document.input.confirmation_password.style.border = "solid 1px black";
   }
   

   
   
   
   return( true );
}

</script>
<h1>Nuevo Empleado</h1>

<div id="Error"></div>

<form name="input" action="/empleados/create" method="get" onsubmit="return(validateEmpleado());">
<table>
		<tr> 
			<td>Nombre:</td> 
			<td><input type="text" name="nombre" ></td> 
		<tr>
 		<tr>
 			<td>Correo Electronico: </td> 
 			<td><input type="text" name="correo_electronico" > </td> 
 		<tr>

		<tr>
 			<td>RFC:</td> 
 			<td><input type="text" name="rfc" ></td> 
 		<tr>
 
        <tr>
 			<td>Empresa: </td> 
 			<td><select name="empresa_id">
			    <option hidden="true" value='0'>Seleccione una empresa</option>
			    <%@empresas.each do |empresa| %>
	

			    	<option value=<%= empresa.id %> > <%= empresa.nombre %> </option>
			    <% end %>
			</select>
			</td>
 		<!--	<td><input type="text" name="empresa_id" ></td> --> 
 		<tr>

		<tr>
 			<td>Password: </td> 
 			<td><input type="password" name="password" ></td> 
 		<tr>

		<tr>
 			<td>Confirmacion Password:</td> 
 			<td> <input type="password" name="confirmation_password" ></td> 
 		<tr>
 


</table>
<input type="submit" value="Submit">
</form>

app/views/empleados/show.html.erb
<h1>Empleados#show</h1>
<p>Find me in app/views/empleados/show.html.erb</p>

app/views/empresas/create.html.erb
<h1>Empresas#create</h1>
<p>Find me in app/views/empresas/create.html.erb</p>

app/views/empresas/destroy.html.erb
<h1>Empresas#destroy</h1>
<p>Find me in app/views/empresas/destroy.html.erb</p>

app/views/empresas/edit.html.erb
<script type="text/javascript">

function validateEmpresa()
{
 
   if( document.input.nombre.value == "" )
   {
   	 document.getElementById("Error").innerHTML="<li>Error: Nombre es necesario para crear unas nueva sucursal</li>";
   	 //document.getElementById("Error").style.border = "solid 1px red";
     //alert( "Nombre es necesario para crear unas nueva sucursal!" );
     document.input.nombre.focus() ;
     document.input.nombre.style.border = "solid 1px red";
     return false;
   }else
   {
   	document.input.nombre.style.border = "solid 1px black";
   }
   
   
   
   if( document.input.numero_int.value != "" &&
           isNaN( document.input.numero_int.value ) )
   {
   	document.getElementById("Error").innerHTML="<li>Error: Numero Interior debe ser un numero</li>";
   	 
     //alert( "Numero Interior debe ser un numero" );
     document.input.numero_int.focus() ;
     document.input.numero_int.style.border = "solid 1px red";
     return false;
   }
   else
   {
   	document.input.numero_int.style.border = "solid 1px black";
   }
   
   if( document.input.numero_ext.value != "" &&
           isNaN( document.input.numero_ext.value ) )
   {
   	document.getElementById("Error").innerHTML="<li>Error: Numero Exterior debe ser un numero</li>";
     //alert( "Numero Exterior debe ser un numero" );
     document.input.numero_ext.style.border = "solid 1px red";
     document.input.numero_ext.focus() ;
     return false;
   }
   else
   {
   	document.input.numero_ext.style.border = "solid 1px black";
   }
   
   if( document.input.codigo_postal.value != "" &&(
           isNaN( document.input.codigo_postal.value ) ||
           document.input.codigo_postal.value.length != 5 ))
   {
   	 document.getElementById("Error").innerHTML="<li>Error: Codigo postal debe ser 5 numeros #####.</li>";
     //alert( "Codigo postal debe ser 5 numeros #####." );
     document.input.codigo_postal.focus() ;
     return false;
   }
   else
   {
   	document.input.codigo_postal.style.border = "solid 1px black";
   }
   
   return( true );
}

</script>

<h1>Editar Sucursal</h1>
<div id="Error"></div>
<form name="input" action="/empresas/create" method="get" onsubmit="return(validateEmpresa());">
<table>
	<input type="hidden" name="id" value="<%=@empresa.id%>">
		<tr> 
			<td>Nombre:</td> 
			<td><input type="text" name="nombre" value=<%=@empresa.nombre%> </td> 
		<tr>
 		<tr>
 			<td>Calle: </td> 
 			<td><input type="text" name="calle" value=<%=@empresa.calle%>></td> 
 		<tr>

		<tr>
 			<td>Colonia:</td> 
 			<td><input type="text" name="colonia" value=<%=@empresa.colonia%>></td> 
 		<tr>
 
        <tr>
 			<td>Numero Exterior: </td> 
 			<td><input type="text" name="numero_ext" value=<%=@empresa.numero_ext%>></td> 
 		<tr>

		<tr>
 			<td>Numero Interior: </td> 
 			<td><input type="text" name="numero_int" value=<%=@empresa.numero_int%>></td> 
 		<tr>

		<tr>
 			<td>Codigo Postal:</td> 
 			<td> <input type="text" name="codigo_postal" value=<%=@empresa.codigo_postal%>></td> 
 		<tr>

		<tr>
			<td>Ciudad:</td> 
			<td> <input type="text" name="ciudad" value=<%=@empresa.ciudad%>></td> 
		<tr>

		<tr>
			<td>Pais:</td> 
			<td><input type="text" name="pais" value=<%=@empresa.pais%>></td> 
		<tr>

</table>
<input type="submit" value="Submit">
</form>

<h2>Listado de Empleado de Sucursal</h2>
<% if @empleados != nil %>
	
	<table style="width:80%">
	<tr>
	  <th>Nombre</th>
	  <th>Correo Electronico</th> 
	  <th>RFC</th>
	  <th>Empresa id</th>
	  <th></th>
	  <th></th>
	  <th></th>
	</tr>
	
	
	<%@empleados.each do |empleado| %>
	<tr>
	  <td><%= empleado.nombre %></td>
	  <td><%= empleado.correo_electronico %></td> 
	  <td><%= empleado.rfc %></td>
	  <td><%= empleado.empresa_id %></td>
	  
      
	  
      <td><%= link_to 'Modificar', edit_empleado_path(empleado) %></td>
      <td><%= link_to 'Eliminar', empleado, method: :delete,
                                     data: { confirm: 'Estas seguro?' } %></td>
	</tr>
	<% end %>
	</table>
<% else %>
	
	<h2>No hay empleados a mostrar</h2>

<% end %>
<br>

<%= link_to "Agregar Empleado", controller: 'empleados', action: 'new' %>

app/views/empresas/index.html.erb
<h1>Listado de Sucursales</h1>
<% if @empresas != nil %>
	<h2>Sucursales existentes</h2>
	<table border="1" style="width:900px">
	<tr>
	  <th>Nombre</th>
	  <th>Calle</th> 
	  <th>Numero ext</th>
	  <th>Numero int</th>
	  <th>Codigo Postal</th>
	  <th>Ciudad</th>
	  <th>Pais</th>
	  <th></th>
	  <th></th>
	  
	</tr>
	
	
	<%@empresas.each do |empresa| %>
	<tr>
	  <td><%= empresa.nombre %></td>
	  <td><%= empresa.calle %></td> 
	  <td><%= empresa.numero_ext %> </td>
	  <td><%= empresa.numero_int %> </td>
	  <td><%= empresa.codigo_postal %> </td>
	  <td><%= empresa.ciudad %> </td>
	  <td><%= empresa.pais %> </td>
      
	  
      <td><%= link_to 'Modificar', edit_empresa_path(empresa) %></td>
      <td><%= link_to 'Eliminar', empresa, method: :delete,
                                     data: { confirm: 'Estas seguro?' } %></td>
	</tr>
	<% end %>
	</table>
<% else %>
	
	<h2>No hay empresas a mostrar</h2>

<% end %>
<br>
<%= link_to "Agregar Sucursal", new_empresa_path %> <br>
<%= link_to "Agregar Empleado", new_empleado_path %>

app/views/empresas/new.html.erb
<script type="text/javascript">

function validateEmpresa()
{
 
   if( document.input.nombre.value == "" )
   {
   	 document.getElementById("Error").innerHTML="<li>Error: Nombre es necesario para crear unas nueva sucursal</li>";
   	 //document.getElementById("Error").style.border = "solid 1px red";
     //alert( "Nombre es necesario para crear unas nueva sucursal!" );
     document.input.nombre.focus() ;
     document.input.nombre.style.border = "solid 1px red";
     return false;
   }else
   {
   	document.input.nombre.style.border = "solid 1px black";
   }
   
   
   
   if( document.input.numero_int.value != "" &&
           isNaN( document.input.numero_int.value ) )
   {
   	document.getElementById("Error").innerHTML="<li>Error: Numero Interior debe ser un numero</li>";
   	 
     //alert( "Numero Interior debe ser un numero" );
     document.input.numero_int.focus() ;
     document.input.numero_int.style.border = "solid 1px red";
     return false;
   }
   else
   {
   	document.input.numero_int.style.border = "solid 1px black";
   }
   
   if( document.input.numero_ext.value != "" &&
           isNaN( document.input.numero_ext.value ) )
   {
   	document.getElementById("Error").innerHTML="<li>Error: Numero Exterior debe ser un numero</li>";
     //alert( "Numero Exterior debe ser un numero" );
     document.input.numero_ext.style.border = "solid 1px red";
     document.input.numero_ext.focus() ;
     return false;
   }
   else
   {
   	document.input.numero_ext.style.border = "solid 1px black";
   }
   
   if( document.input.codigo_postal.value != "" &&(
           isNaN( document.input.codigo_postal.value ) ||
           document.input.codigo_postal.value.length != 5 ))
   {
   	 document.getElementById("Error").innerHTML="<li>Error: Codigo postal debe ser 5 numeros #####.</li>";
     //alert( "Codigo postal debe ser 5 numeros #####." );
     document.input.codigo_postal.focus() ;
     return false;
   }
   else
   {
   	document.input.codigo_postal.style.border = "solid 1px black";
   }
   
   return( true );
}

function validateEmpleado()
{
 
   if( document.input.nombre.value == "" )
   {
   	 document.getElementById("Error").innerHTML+="<li>Error: Nombre del empleado es necesario para crear un nuevo empleado</li>";
     //alert( "Nombre del empleado es necesario para crear un nuevo empleado" );
     document.input.nombre.focus() ;
     return false;
   }
   if( document.input.correo_electronico.value == "" )
   {
   	 document.getElementById("Error").innerHTML+="<li>Error: Correo Electronico es necesario para crear un nuevo empleado</li>";
     alert( "Correo Electronico es necesario para crear un nuevo empleado" );
     document.input.correo_electronico.focus() ;
     return false;
   }
   if( document.input.rfc.value == "" )
   {
     alert( "RFC es necesario para crear un nuevo empleado" );
     document.input.rfc.focus() ;
     return false;
   }if( document.input.empresa_id.value == "" )
   {
     alert( "Empresa es necesaria para crear un nuevo empleado" );
     document.input.empresa_id.focus() ;
     return false;
   }
   if( document.input.password.value == "" )
   {
     alert( "Password es necesario para crear un nuevo empleado" );
     document.input.password.focus() ;
     return false;
   }
   
   if( document.input.password.value != document.confirmacion_password.value )
   {
     alert( "Tu Password y su Confirmacion no concuerdan" );
     document.input.password.focus() ;
     return false;
   }
   
   var emailID = document.input.correo_electronico.value;
   atpos = emailID.indexOf("@");
   dotpos = emailID.lastIndexOf(".");
   if (atpos < 1 || ( dotpos - atpos < 2 )) 
   {
       alert("Por favor escriba un Correo Electronico valido")
       document.input.correo_electronico.focus() ;
       return false;
   }
   
   
   
   return( true );
}


</script>
<h1>Nueva Sucursal</h1>

<div id="Error"><%= %></div>

<form name="input" action="/empresas/create" method="get" onsubmit="return(validateEmpresa());">

	<table>
		<tr> 
			<td>Nombre:</td> 
			<td><input id="nombre" type="text" name="nombre"> </td> 
		<tr>
 		<tr>
 			<td>Calle: </td> 
 			<td><input type="text" name="calle"></td> 
 		<tr>

		<tr>
 			<td>Colonia:</td> 
 			<td><input type="text" name="colonia"></td> 
 		<tr>
 
        <tr>
 			<td>Numero Exterior: </td> 
 			<td><input type="text" name="numero_ext"></td> 
 		<tr>

		<tr>
 			<td>Numero Interior: </td> 
 			<td><input type="text" name="numero_int"></td> 
 		<tr>

		<tr>
 			<td>Codigo Postal:</td> 
 			<td> <input type="text" name="codigo_postal"></td> 
 		<tr>

		<tr>
			<td>Ciudad:</td> 
			<td><input type="text" name="ciudad"></td> 
		<tr>

		<tr>
			<td>Pais:</td> 
			<td><input type="text" name="pais"></td> 
		<tr>

</table>
<input type="submit" value="Submit">
</form>

app/views/empresas/update.html.erb
<h1>Empresas#update</h1>
<p>Find me in app/views/empresas/update.html.erb</p>